[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "KashmiriNormalizer"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["regex"]

[tool.setuptools.packages.find]
where = ["src"]
